In [7]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])
print('A+B=',np.add(A,B))
print('A+B=',np.subtract(A,B))

A+B= [5 7 9]
A+B= [-3 -3 -3]


In [20]:
C = np.array([[1,2,3],
            [1,1,1]])
D = np.array([[4,3,9,9],
             [1,1,2,2],
             [4,2,1,1]])

# 矩阵相乘
print('np.dot(C,D) = ',np.dot(C,D))
print('np.matmul(C,D) = ',np.matmul(C,D))
print('     C@D     = ',np.matmul(C,D))

# 元素与元素相乘，两种方法一样
print('np.multiply(D,D) = ',np.multiply(D,D))
print('     D*D     = ', D*D)


np.dot(C,D) =  [[18 11 16 16]
 [ 9  6 12 12]]
np.matmul(C,D) =  [[18 11 16 16]
 [ 9  6 12 12]]
     C@D     =  [[18 11 16 16]
 [ 9  6 12 12]]
np.multiply(D,D) =  [[16  9 81 81]
 [ 1  1  4  4]
 [16  4  1  1]]
     D*D     =  [[16  9 81 81]
 [ 1  1  4  4]
 [16  4  1  1]]


#### np.dot和np.matmul的区别
1.都是矩阵乘法
2.np.matmul中，禁止矩阵与标量的乘法
3.np.matmul中，在矢量乘矢量的内积运算中，matmul和dot没有区别
4.np.matmul中，多维的矩阵，将前n-2维视为后2维德元素后，进行乘法操作

## Markdown的基本技巧

1. 几个 # 号就可以表示几级标题（最多4级标题）
2. 黑体   **ABC**
3. 斜体   *
4. 引用一段话   >
5. 列出几个观点 （*＋空格）
6. $\pi$  $\sum_{i=1}^{i=n}$     \表示转义符（用的Latax语法）

 **Github** 是程序员必备工具，作为版本控制(version control)和协同合作的利器，让人爱不释手
1. 安装GitHub for windows，注册账户
2. 基本命令
  * git init,建立一个新的repository
  * git clone 克隆一个repository
  * git ass 加入新的内容到缓存区
  * git commit 实际提交改动
  * git push 推送改动到远端
  * git checkout -b 做一个分支branch
  * git pull 获取并合并远端的版本（fetch+merge）
  * git merge 合并其他版本，遇到冲突怎么办？
  * git log 查看记录
#### [参考资料](https://guides.github.com/)
#### 工作区，暂存区，代码库